//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public long id { get; set; }
        public decimal lon { get; set; }
        public decimal lat { get; set; }
        public string name { get; set; }
        public string cuisine { get; set; }
        public string opening_hours { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
    }
}
